### ISSUE TITLE
Check all modes and submodes with MySQL/MariaDB

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/check_bareos#1]
Some modes and submodes are not working with MySQL. Hunt done what does not work and open an issues for every one.

**Comment by widhalmt** [comment]
Mode `status` is done.

**Comment by torcolato** [comment]
While looking at converting the `media` queries i am not sure what the part 
`or lastwritten+(media.volretention * '1 second'::INTERVAL)
`is querying, someone care to explain?

If I get it somehow right (dont know that much about PGSQL) it means an addition of lastwritten with volretention and the INTERVAL function is used to convert between TIMESTAMP and BIGINT???!

If so, something like this might replace the query for `checkEmptyTapes`:

`SELECT Count(MediaId) FROM Media,Pool,Storage WHERE Media.PoolId=Pool.PoolId AND Slot>0 AND InChanger=1 AND Media.StorageId=Storage.StorageId AND (VolStatus like 'Purged' or VolStatus like 'Recycle' or ADDTIME(lastwritten,SEC_TO_TIME(Media.volretention)));`

But not entirely sure if this makes sense :)

**Comment by duven87** [comment]
Hi, why check_bareos.py needs postgresql if my bareos installation its with mysql?
If I dont install postgresql , check_bareos.py doesn work:
CRITICAL - could not connect to server: Connection refused  Is the server running on host "127.0.0.1" and accepting  TCP/IP connections on port 5432?|;;;;

**Comment by martialblog** [comment]
Since there is no active work on this and we might need a major rewrite to reflect the current Bareos releases, I will close this for now. 

The psql/mysql module installation issues were addressed in the latest release
