### ISSUE TITLE
Failed backup not detected if full caused by consolidate job

### ISSUE THREAD

**Issue by HOSTED-POWER** [NETWAYS/check_bareos#14]
Hi,

I just saw failed job with new 16.x consolidate feature (AlwaysIncremental)

`# check_bareos.py -u xxx -p xxx -H localhost -d mysql status --failedBackups
OK - Only 0 Backups failed in the last 7 days|Failed=0;5;10;;`

While there is a failed consolidate job, i.e. the consolidate jobs creates new "full" jobs which consolidate the jobs. One of these jobs failed but not detected by the plugin :(

**Comment by widhalmt** [comment]
Hi!

Thanks for the issue. I'll have to set up a newer testing environment but I will try to fix this soon.

**Comment by HOSTED-POWER** [comment]
Well I'm unsure, maybe it can't detect any failures anymore on 16.2 version :|

**Comment by HOSTED-POWER** [comment]
Well still have issues that failing job is not detected at all in version 16.2.x

OK - Only 0 Backups failed in the last 3 day

While I do have failed consolidate job in last 24 hours.

**Comment by HOSTED-POWER** [comment]
Perhaps any update on this? We still fail to detect when consolidate jobs fail atm... :/

**Comment by martialblog** [comment]
We're currently planning a rewrite that will provide a more flexible CLI to adress this issue

**Comment by HOSTED-POWER** [comment]
Any idea how to detect this? Put the new version, having hanging consolidate job, but undetected :(

'/usr/lib/nagios/plugins/check_bareos.py' '--user' 'xxx' '--password' 'xxx' '--Host' 'xxxx' '--database' 'xxx' 'job' '--runTimeJobs' '--time' '1' '-w' '1' '-c' '1' '-st' 'R'
[OK] - 0.0 Jobs are running longer than 1 days|bareos.job.count=0.0;1;1;;

While we have hanging jobs from a consolidation (virtualfull jobs)

**Comment by HOSTED-POWER** [comment]
ah it works when I leave the state out of it apparently

**Comment by martialblog** [comment]
Hi, glad to hear it's working. 

I'm not sure what the state of hanging jobs would be. The `-st` flag now supports all possible job states, with the default being `'C': 'Job created but not yet running`.

**Comment by HOSTED-POWER** [comment]
What state do I need to specify in this case? I'm not sure if we won't monitor the wrong things if we do not specify the state?

**Comment by martialblog** [comment]
Not sure to be honest. You could check the jobs with the bconsole or  directly in the database and see what state they currently have.
