### ISSUE TITLE
After Upgrade from Buster to Bullseye doesn't work -   /usr/bin/python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by duven87** [NETWAYS/check_bareos#20]
Hi, My system accidentally upgraded stable repo from Buster to Bullesye tonight and the command no longer works.
First I get this error:

 /usr/bin/python: bad interpreter: No such file or directory

Then I changed the script to :

#!/usr/bin/python3

and I get the following error:

root@backup02:/etc/bareos# /usr/lib/nagios/plugins/check_bareos.py
  File "/usr/lib/nagios/plugins/check_bareos.py", line 480
    except psycopg2.DatabaseError, e:
                                 ^
SyntaxError: invalid syntax

Any update please?

**Comment by RincewindsHat** [comment]
Hi @duven87 ,
would you be so kind and test https://github.com/NETWAYS/check_bareos/tree/switch_to_python3 ?

**Comment by duven87** [comment]
hi, thanks for ur fast answer, unfortunately...
```
./check_bareos.py: line 7: syntax error near unexpected token `newline'
./check_bareos.py: line 7: `<!DOCTYPE html>'
```

**Comment by duven87** [comment]
Hi, thanks for ur answer:

```
Traceback (most recent call last):
  File "/etc/bareos/./check_bareos.py", line 25, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```

**Comment by duven87** [comment]
SOLVED:
Im not sure which worked finally (pip install sure but apt packets maybe some dont need it)

sudo apt-get install libmariadb-dev-compat  libmariadb-dev  python-pip  python3-pip python-psycopg2
pip install psycopg2-binary
pip install mysqlclient pymysql

**Comment by RincewindsHat** [comment]
Ah, thank you. If the checks work correctly we can merge that into master.

**Comment by duven87** [comment]
yes, now works. I have critical:

```
root@backup02:/etc/bareos# ./check_bareos.py -u bareos -p xxxx -d p status -e -f -w 1 -c 5
CRITICAL - could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?|;;;;
```
but I'm not sure it's the check's fault... I'm still trying to fix more things since the update.

**Comment by RincewindsHat** [comment]
Sweet! 
hm, good question. maybe we have to add a `port` option to the plugin

**Comment by duven87** [comment]
I think I am realising that there is no need to change the check. Because I'm testing the old one and it works too.
You just have to reinstall the modules I mentioned before.

**Comment by RincewindsHat** [comment]
hm, switching to Python3 will be necessary in any case. In the long term, support for Python2 will be dropped from all distributions anyway.
