### ISSUE TITLE
Missing PSQL connection

### ISSUE THREAD

**Issue by TheCry** [NETWAYS/check_bareos#27]
In version 1.0.2 there was still possible to use the script with PosgreSQL.
`parser.add_argument('-d', '--database', dest='database', choices=['mysql', 'm', 'postgresql', 'p', 'psql'], default='mysql', help='the database kind for the database connection (m=mysql, p=psql) (Default=Mysql)')`

After version 20 Bareos doesn't support MySQL anymore.
It will be greate if you add PostgreSQL support
Thanks
Regards
Sascha

**Comment by martialblog** [comment]
Hi, are you using the latest version? It now only supports PostgreSQL and the `-d` flag was repurposed to mean the database name

**Comment by TheCry** [comment]
Oh my god..Sometimes i'm  little bit blind. Yes i'm using the last version and without -d it works perfect.. Sorry
