### ISSUE TITLE
[Feature]: Use director configuration for DB access

### ISSUE THREAD

**Issue by mowgli** [NETWAYS/check_bareos#36]
### Describe the feature request

As it is always a security issue to specify password on command line, it would be better to receive the DB credentials from bareos director directly.

**Comment by martialblog** [comment]
Hi, thanks for the issue. Yes it is a bit problematic. 

By "from bareos director" you mean the director's configuration file? Could be an option, but we also got to consider that the machine running the check plugin, might be a different machine. Also then we have to parse the configuration format, which I think is a custom format. 

What it quick to implement is reading the password from an environment variable.

**Comment by martialblog** [comment]
I tried to prototype something here https://github.com/NETWAYS/check_bareos/tree/feature/password-file

Feedback is welcome

**Comment by martialblog** [comment]
Fixed in https://github.com/NETWAYS/check_bareos/pull/37

There are options to use ENV variables and a file

**Comment by mowgli** [comment]
I tested the implementation. Works well. Thanks for fixing it that fast.

However, I cannot use the bareos configuration itself as the db password is named `dbpassword` (all small and in one word).

But that would be no bad as I should configure the check to run as user nagios which gets its own password file.
