### ISSUE TITLE
[Bug]: minor: Alarm level should be including

### ISSUE THREAD

**Issue by mowgli** [NETWAYS/check_bareos#38]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

2.1.0

### Describe the bug

The warning level for nagios checks is normally assumed to be inclusive. If the warning is set to 2 all equal and greater then 2 should create a warning. But at least with the command below, the warning is only issued when it is greater (not equal).

### How to recreate the bug?

```
/usr/local/lib/nagios/plugins/check_bareos -U bareos --password-file /etc/bareos/db-password status --failedBackups --warning 2 --critical 5
```

**Comment by martialblog** [comment]
Hi, 

The plugin supports the Threshold format: https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

If I read the docs correctly, it should work as expected? @RincewindsHat Second opinion please

```
10 	< 0 or > 10, (outside the range of {0 .. 10})

check_stuff -w10 -c20 	Critical if "stuff" is over 20, else warn
 if over 10 (will be critical if "stuff" is less than 0)
```

**Comment by RincewindsHat** [comment]
@martialblog this is correct.

**Comment by martialblog** [comment]
We gonna update the README to make things clearer.

**Comment by martialblog** [comment]
Updated the README. Gonna close this for now
