### ISSUE TITLE
ident authentication failed for user "bareos"

### ISSUE THREAD

**Issue by marcelfischer** [NETWAYS/check_bareos#8]
Hey Thomas,

I tried your plugin for bareos. But I always get ident authentication failed for user "bareos".
The user is okay I think. No password is set.

I think it has something to do with postgres. But my knowledge of authentication with postgres is quite limited.

Do you have an idea?

best regards,
Marcel

**Comment by widhalmt** [comment]
Hi,

I'm more of a MySQL gui, too, but I will look into it, as soon as my other task which consumed all of my spare time in the last months is done. Should be the case within days now.

So sorry for the late answer,

Cheers,
Thomas
